/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWalkthroughsRouteImport } from './routes/_app.walkthroughs'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppConfigRouteImport } from './routes/_app.config'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAddressRouteImport } from './routes/_app.address'
import { Route as AppWizardMenuRouteImport } from './routes/_app.wizard.menu'
import { Route as AppWizardLockboxRouteImport } from './routes/_app.wizard.lockbox'
import { Route as AppWizardFrontPhotoRouteImport } from './routes/_app.wizard.front-photo'
import { Route as AppWizardFixMissingRouteImport } from './routes/_app.wizard.fix-missing'
import { Route as AppWizardExteriorPaintRouteImport } from './routes/_app.wizard.exterior-paint'
import { Route as AppWizardCompleteRouteImport } from './routes/_app.wizard.complete'
import { Route as AppWizardChecklistRouteImport } from './routes/_app.wizard.checklist'
import { Route as AppReviewIdRouteImport } from './routes/_app.review.$id'
import { Route as AppWizardQQidRouteImport } from './routes/_app.wizard.q.$qid'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalkthroughsRoute = AppWalkthroughsRouteImport.update({
  id: '/walkthroughs',
  path: '/walkthroughs',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAddressRoute = AppAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => AppRoute,
} as any)
const AppWizardMenuRoute = AppWizardMenuRouteImport.update({
  id: '/wizard/menu',
  path: '/wizard/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppWizardLockboxRoute = AppWizardLockboxRouteImport.update({
  id: '/wizard/lockbox',
  path: '/wizard/lockbox',
  getParentRoute: () => AppRoute,
} as any)
const AppWizardFrontPhotoRoute = AppWizardFrontPhotoRouteImport.update({
  id: '/wizard/front-photo',
  path: '/wizard/front-photo',
  getParentRoute: () => AppRoute,
} as any)
const AppWizardFixMissingRoute = AppWizardFixMissingRouteImport.update({
  id: '/wizard/fix-missing',
  path: '/wizard/fix-missing',
  getParentRoute: () => AppRoute,
} as any)
const AppWizardExteriorPaintRoute = AppWizardExteriorPaintRouteImport.update({
  id: '/wizard/exterior-paint',
  path: '/wizard/exterior-paint',
  getParentRoute: () => AppRoute,
} as any)
const AppWizardCompleteRoute = AppWizardCompleteRouteImport.update({
  id: '/wizard/complete',
  path: '/wizard/complete',
  getParentRoute: () => AppRoute,
} as any)
const AppWizardChecklistRoute = AppWizardChecklistRouteImport.update({
  id: '/wizard/checklist',
  path: '/wizard/checklist',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewIdRoute = AppReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppWizardQQidRoute = AppWizardQQidRouteImport.update({
  id: '/wizard/q/$qid',
  path: '/wizard/q/$qid',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/address': typeof AppAddressRoute
  '/admin': typeof AppAdminRoute
  '/config': typeof AppConfigRoute
  '/profile': typeof AppProfileRoute
  '/walkthroughs': typeof AppWalkthroughsRoute
  '/review/$id': typeof AppReviewIdRoute
  '/wizard/checklist': typeof AppWizardChecklistRoute
  '/wizard/complete': typeof AppWizardCompleteRoute
  '/wizard/exterior-paint': typeof AppWizardExteriorPaintRoute
  '/wizard/fix-missing': typeof AppWizardFixMissingRoute
  '/wizard/front-photo': typeof AppWizardFrontPhotoRoute
  '/wizard/lockbox': typeof AppWizardLockboxRoute
  '/wizard/menu': typeof AppWizardMenuRoute
  '/wizard/q/$qid': typeof AppWizardQQidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/address': typeof AppAddressRoute
  '/admin': typeof AppAdminRoute
  '/config': typeof AppConfigRoute
  '/profile': typeof AppProfileRoute
  '/walkthroughs': typeof AppWalkthroughsRoute
  '/review/$id': typeof AppReviewIdRoute
  '/wizard/checklist': typeof AppWizardChecklistRoute
  '/wizard/complete': typeof AppWizardCompleteRoute
  '/wizard/exterior-paint': typeof AppWizardExteriorPaintRoute
  '/wizard/fix-missing': typeof AppWizardFixMissingRoute
  '/wizard/front-photo': typeof AppWizardFrontPhotoRoute
  '/wizard/lockbox': typeof AppWizardLockboxRoute
  '/wizard/menu': typeof AppWizardMenuRoute
  '/wizard/q/$qid': typeof AppWizardQQidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/address': typeof AppAddressRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/walkthroughs': typeof AppWalkthroughsRoute
  '/_app/review/$id': typeof AppReviewIdRoute
  '/_app/wizard/checklist': typeof AppWizardChecklistRoute
  '/_app/wizard/complete': typeof AppWizardCompleteRoute
  '/_app/wizard/exterior-paint': typeof AppWizardExteriorPaintRoute
  '/_app/wizard/fix-missing': typeof AppWizardFixMissingRoute
  '/_app/wizard/front-photo': typeof AppWizardFrontPhotoRoute
  '/_app/wizard/lockbox': typeof AppWizardLockboxRoute
  '/_app/wizard/menu': typeof AppWizardMenuRoute
  '/_app/wizard/q/$qid': typeof AppWizardQQidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/address'
    | '/admin'
    | '/config'
    | '/profile'
    | '/walkthroughs'
    | '/review/$id'
    | '/wizard/checklist'
    | '/wizard/complete'
    | '/wizard/exterior-paint'
    | '/wizard/fix-missing'
    | '/wizard/front-photo'
    | '/wizard/lockbox'
    | '/wizard/menu'
    | '/wizard/q/$qid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/address'
    | '/admin'
    | '/config'
    | '/profile'
    | '/walkthroughs'
    | '/review/$id'
    | '/wizard/checklist'
    | '/wizard/complete'
    | '/wizard/exterior-paint'
    | '/wizard/fix-missing'
    | '/wizard/front-photo'
    | '/wizard/lockbox'
    | '/wizard/menu'
    | '/wizard/q/$qid'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_app/address'
    | '/_app/admin'
    | '/_app/config'
    | '/_app/profile'
    | '/_app/walkthroughs'
    | '/_app/review/$id'
    | '/_app/wizard/checklist'
    | '/_app/wizard/complete'
    | '/_app/wizard/exterior-paint'
    | '/_app/wizard/fix-missing'
    | '/_app/wizard/front-photo'
    | '/_app/wizard/lockbox'
    | '/_app/wizard/menu'
    | '/_app/wizard/q/$qid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/walkthroughs': {
      id: '/_app/walkthroughs'
      path: '/walkthroughs'
      fullPath: '/walkthroughs'
      preLoaderRoute: typeof AppWalkthroughsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/address': {
      id: '/_app/address'
      path: '/address'
      fullPath: '/address'
      preLoaderRoute: typeof AppAddressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wizard/menu': {
      id: '/_app/wizard/menu'
      path: '/wizard/menu'
      fullPath: '/wizard/menu'
      preLoaderRoute: typeof AppWizardMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wizard/lockbox': {
      id: '/_app/wizard/lockbox'
      path: '/wizard/lockbox'
      fullPath: '/wizard/lockbox'
      preLoaderRoute: typeof AppWizardLockboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wizard/front-photo': {
      id: '/_app/wizard/front-photo'
      path: '/wizard/front-photo'
      fullPath: '/wizard/front-photo'
      preLoaderRoute: typeof AppWizardFrontPhotoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wizard/fix-missing': {
      id: '/_app/wizard/fix-missing'
      path: '/wizard/fix-missing'
      fullPath: '/wizard/fix-missing'
      preLoaderRoute: typeof AppWizardFixMissingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wizard/exterior-paint': {
      id: '/_app/wizard/exterior-paint'
      path: '/wizard/exterior-paint'
      fullPath: '/wizard/exterior-paint'
      preLoaderRoute: typeof AppWizardExteriorPaintRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wizard/complete': {
      id: '/_app/wizard/complete'
      path: '/wizard/complete'
      fullPath: '/wizard/complete'
      preLoaderRoute: typeof AppWizardCompleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wizard/checklist': {
      id: '/_app/wizard/checklist'
      path: '/wizard/checklist'
      fullPath: '/wizard/checklist'
      preLoaderRoute: typeof AppWizardChecklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review/$id': {
      id: '/_app/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof AppReviewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wizard/q/$qid': {
      id: '/_app/wizard/q/$qid'
      path: '/wizard/q/$qid'
      fullPath: '/wizard/q/$qid'
      preLoaderRoute: typeof AppWizardQQidRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAddressRoute: typeof AppAddressRoute
  AppAdminRoute: typeof AppAdminRoute
  AppConfigRoute: typeof AppConfigRoute
  AppProfileRoute: typeof AppProfileRoute
  AppWalkthroughsRoute: typeof AppWalkthroughsRoute
  AppReviewIdRoute: typeof AppReviewIdRoute
  AppWizardChecklistRoute: typeof AppWizardChecklistRoute
  AppWizardCompleteRoute: typeof AppWizardCompleteRoute
  AppWizardExteriorPaintRoute: typeof AppWizardExteriorPaintRoute
  AppWizardFixMissingRoute: typeof AppWizardFixMissingRoute
  AppWizardFrontPhotoRoute: typeof AppWizardFrontPhotoRoute
  AppWizardLockboxRoute: typeof AppWizardLockboxRoute
  AppWizardMenuRoute: typeof AppWizardMenuRoute
  AppWizardQQidRoute: typeof AppWizardQQidRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddressRoute: AppAddressRoute,
  AppAdminRoute: AppAdminRoute,
  AppConfigRoute: AppConfigRoute,
  AppProfileRoute: AppProfileRoute,
  AppWalkthroughsRoute: AppWalkthroughsRoute,
  AppReviewIdRoute: AppReviewIdRoute,
  AppWizardChecklistRoute: AppWizardChecklistRoute,
  AppWizardCompleteRoute: AppWizardCompleteRoute,
  AppWizardExteriorPaintRoute: AppWizardExteriorPaintRoute,
  AppWizardFixMissingRoute: AppWizardFixMissingRoute,
  AppWizardFrontPhotoRoute: AppWizardFrontPhotoRoute,
  AppWizardLockboxRoute: AppWizardLockboxRoute,
  AppWizardMenuRoute: AppWizardMenuRoute,
  AppWizardQQidRoute: AppWizardQQidRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
